# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: hauleye
    build: .
    command: gunicorn -b 0.0.0.0:5000 hauleye.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/hauleye.db
    volumes:
      - ./hauleye:/code/hauleye
      - ./db/:/db/
    ports:
      - "5000:5000"
